### ISSUE TITLE
Conv3d or Conv4d in SCR

### ISSUE THREAD

**Issue by csyanbin** [dahyun-kang/renet#1]
Hi, thanks for releasing the organized code. 

I find that in the code SCR is implemented with Conv3d, while in the paper it is Conv4d. Does this matter?

**Comment by dahyun-kang** [comment]
Hello, thank you for raising the first issue.

It does not matter since 1 * 1 * 3 * 3 convolution is implemented as 1 * 3 * 3 convolution. 
To do so, we first flatten the input spatial dimension of H * W * U * V to HW * U * V and do the 1 * 3 * 3 convolution over the input.
PyTorch does not officially support Conv4d as far as I know, so we needed such trick.

Have a great day! :smiley:
