### ISSUE TITLE
Is there an easy way to save checkpoints for Colab user?

### ISSUE THREAD

**Issue by ChiaraDom18** [dahyun-kang/renet#3]
The question is very simple: how can I save the training checkpoints in the guide and then resume them?

**Comment by dahyun-kang** [comment]
Hello,

**This code does not provide a resume option at this point** because training RENet takes a few hours so I used to wait and see 😃.  

You may want to use the `-save_all` option for the first run and `load_model` function for the subsequent run to load the last checkpoint that you saved in the first run. Also, the optimizer should be properly loaded as well, which the official code does not provide.

Below are the code snippets you might want to refer to:

* 🔽 Use the `-save_all` argument for the first run.
https://github.com/dahyun-kang/renet/blob/ee315c17764694175fc8bd0d0a28eb712ec768b7/common/utils.py#L149

* 🔽 Call the `load_model` function right after this line below so that the checkpoint is properly loaded to the model.
https://github.com/dahyun-kang/renet/blob/ee315c17764694175fc8bd0d0a28eb712ec768b7/train.py#L92-L93

* 🔽 Here is the `load_model` function in `common/utils.py`.
https://github.com/dahyun-kang/renet/blob/ee315c17764694175fc8bd0d0a28eb712ec768b7/common/utils.py#L76


Have a great day! 😃
